language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - hhvm
    - 7

services:
    - redis-server

before_script:
    - composer selfupdate
    - composer install --prefer-source

script: ./vendor/bin/phpunit
